#import "./MovieFragment.gql"

query movies($limit: Int, $page: Int, $title: String, $sort: String, $sortDirection: String) {
  moviesList: moviesList(limit: $limit, page: $page, title: $title, sort: $sort, sortDirection: $sortDirection) {
    totalCount,
    movies {
      ...movie
    }
  }
}
