#import "./SeriesFragment.gql"

query series($limit: Int, $page: Int, $title: String, $sort: String, $sortDirection: String) {
  seriesList: seriesList(limit: $limit, page: $page, title: $title, sort: $sort, sortDirection: $sortDirection) {
    totalCount,
    series {
      ...series
    }
  }
}
