# Script for populating the Mongo database. You can run it as:
#
#     mix run priv/repo/seeds_mongo.exs

# Mongo.find(:mongo, "collection", %%{}, limit: 20)

Mongo.delete_many!(:mongo, "series", %{})
Mongo.insert_many!(:mongo, "series", [
  %{
  	imdb_id: "tt0460681",
  	title: "Supernatural",
  	release_date: "2005-09-13",
  	runtime: "44 min",
  	classification: "PG",
  	genres: ["Drama", "Fantasy", "Horror", "Mystery", "Thriller"],
  	writers: ["Eric Kripke"],
  	actors: [
		%{name: "Jared Padalecki", character: "Sam Winchester", protagonist: true},
		%{name: "Jensen Ackles", character: "Dean Winchester", protagonist: true},
		%{name: "Misha Collins", character: "Castiel"},
		%{name: "Mark Sheppard", character: "Crowley"},
		%{name: "Jim Beaver", character: "Bobby Singer"},
		%{name: "Samantha Smith", character: "Mary Winchester"},
		%{name: "Mark Pellegrino", character: "Lucifer"},
		%{name: "Ruth Connell", character: "Rowena MacLeod"},
		%{name: "Alexander Calvert", character: "Jack"},
		%{name: "Osric Chau", character: "Kevin Tran"},
		%{name: "David Haydn-Jones", character: "Arthur Ketch"},
		%{name: "Kim Rhodes", character: "Sheriff Jody Mills"},
		%{name: "Curtis Armstrong", character: "Metatron"},
		%{name: "Jeffrey Dean Morgan", character: "John Winchester"},
		%{name: "Rob Benedict", character: "Chuck Shurley"},
		%{name: "Genevieve Padalecki", character: "Ruby"},
		%{name: "Richard Speight Jr.", character: "Gabriel"},
		%{name: "Cindy Sampson", character: "Lisa Braeden"},
		%{name: "Lisa Berry", character: "Billie"},
		%{name: "Felicia Day", character: "Charlie Bradbury"},
		%{name: "Amanda Tapping", character: "Naomi"},
		%{name: "Samantha Ferris", character: "Ellen Harvelle"},
		%{name: "Ty Olsson", character: "Benny Lafitte"},
		%{name: "Emily Swallow", character: "Amara (Adult)"},
		%{name: "Erica Carroll", character: "Hannah"},
		%{name: "Mitch Pileggi", character: "Samuel Campbell"},
		%{name: "Kurt Fuller", character: "Zachariah"},
		%{name: "Alaina Huffman", character: "Abaddon"},
		%{name: "Keith Szarabajka", character: "Donatello Redfield"},
		%{name: "Erica Cerra", character: "Duma"}
  	],
  	description: "Two brothers follow their father's footsteps as hunters, fighting evil supernatural beings of many kinds, including monsters, demons, and gods that roam the earth.",
  	languages: ["English"],
  	countries: ["USA"],
  	poster: "https://m.media-amazon.com/images/M/MV5BMjZmYWYwNWMtNGVjNy00NjA4LTgwODQtMThjODNlNjA4ZDdlXkEyXkFqcGdeQXVyNjg3MDMxNzU@._V1_SX300.jpg",
  	seasons: 15
  },
  %{
  	imdb_id: "tt0903747",
  	title: "Breaking Bad",
  	release_date: "2008-01-20",
  	runtime: "49 min",
  	classification: "14A",
  	genres: ["Crime", "Drama", "Thriller"],
  	writers: ["Vince Gilligan"],
  	actors: [
		%{name: "Bryan Cranston", character: "Walter White", protagonist: true},
		%{name: "Anna Gunn", character: "Skyler White", protagonist: true},
		%{name: "Aaron Paul", character: "Jesse Pinkman", protagonist: true},
		%{name: "Dean Norris", character: "Hank Schrader", protagonist: true},
		%{name: "Betsy Brandt", character: "Marie Schrader", protagonist: true},
		%{name: "RJ Mitte", character: "Walter White, Jr.", protagonist: true},		
		%{name: "Bob Odenkirk", character: "Saul Goodman"},
		%{name: "Steven Michael Quezada", character: "Steven Gomez"},
		%{name: "Jonathan Banks", character: "Mike Ehrmantraut"},
		%{name: "Giancarlo Esposito", character: "Gustavo 'Gus' Fring"},
		%{name: "Charles Baker", character: "Skinny Pete"},
		%{name: "Jesse Plemons", character: "Todd"},
		%{name: "Christopher Cousins", character: "Ted Beneke"},
		%{name: "Laura Fraser", character: "Lydia Rodarte-Quayle"},
		%{name: "Matt Jones", character: "Badger"},
		%{name: "Lavell Crawford", character: "Huell"},
		%{name: "Ray Campbell", character: "Tyrus Kitt"},
		%{name: "Krysten Ritter", character: "Jane Margolis"},
		%{name: "Kevin Rankin", character: "Kenny"},
		%{name: "Daniel Moncada", character: "Leonel Salamanca"}
  	],
  	description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
  	languages: ["English", "Spanish"],
  	countries: ["USA"],
  	poster: "https://m.media-amazon.com/images/M/MV5BMjhiMzgxZTctNDc1Ni00OTIxLTlhMTYtZTA3ZWFkODRkNmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
  	seasons: 5,
  	spinoffs: [
      %{imdb_id: "tt3032476", title: "Better Call Saul"}
    ]
  },
  %{
  	imdb_id: "tt3032476",
  	title: "Better Call Saul",
  	release_date: "2015-02-08",
  	runtime: "46 min",
  	classification: "PG",
  	genres: ["Crime", "Drama"],
  	writers: ["Vince Gilligan", "Peter Gould"],
  	actors: [
  		%{name: "Bob Odenkirk", character: "Jimmy McGill", protagonist: true},		
		%{name: "Jonathan Banks", character: "Mike Ehrmantraut", protagonist: true},		
		%{name: "Rhea Seehorn", character: "Kim Wexler", protagonist: true},		
		%{name: "Patrick Fabian", character: "Howard Hamlin", protagonist: true},		
		%{name: "Michael Mando", character: "Nacho Varga", protagonist: true},		
		%{name: "Michael McKean", character: "Chuck McGill"},
		%{name: "Giancarlo Esposito", character: "Gustavo 'Gus' Fring"},
		%{name: "Mark Margolis", character: "Hector Salamanca"},
		%{name: "Kerry Condon", character: "Stacey Ehrmantraut"},
		%{name: "Cara Pifko", character: "Paige Novick"},
		%{name: "John Christian Love", character: "Ernesto"},
		%{name: "Vincent Fuentes", character: "Arturo"},
		%{name: "Josh Fadem", character: "Camera Guy"},
		%{name: "Jeremiah Bitsui", character: "Victor"},
		%{name: "Julian Bonfiglio", character: "Sound Guy"},
		%{name: "Tina Parker", character: "Francesca Liddy"},
		%{name: "Eileen Fogarty", character: "Mrs. Nguyen"},
		%{name: "Rex Linn", character: "Kevin Wachtell"},
		%{name: "Dennis Boutsikaris", character: "Rick Schweikart"},
		%{name: "Ray Campbell", character: "8 episodes, 2017-2018"}
  	],
  	description: "The trials and tribulations of criminal lawyer, Jimmy McGill, in the time leading up to establishing his strip-mall law office in Albuquerque, New Mexico.",
  	languages: ["English", "Spanish", "Vietnamese"],
  	countries: ["USA"],
  	poster: "https://m.media-amazon.com/images/M/MV5BMTAxOTQ0MjUzMzJeQTJeQWpwZ15BbWU4MDY0NTAxNzMx._V1_SX300.jpg",
  	seasons: 5
  },
  %{
  	imdb_id: "tt7366338",
  	title: "Chernobyl",
  	release_date: "2019-05-06",
  	runtime: "330 min",
  	classification: "13+",
  	genres: ["Drama", "History", "Thriller"],
  	writers: ["Craig Mazin"],
  	actors: [
		%{name: "Jessie Buckley", character: "Lyudmilla Ignatenko", protagonist: true},		
		%{name: "Jared Harris", character: "Valery Legasov", protagonist: true},		
		%{name: "Stellan Skarsgård", character: "Boris Shcherbina", protagonist: true},		
		%{name: "Adam Nagaitis", character: "Vasily Ignatenko"},
		%{name: "Emily Watson", character: "Ulana Khomyuk"},
		%{name: "Paul Ritter", character: "Anatoly Dyatlov"},
		%{name: "Robert Emms", character: "Leonid Toptunov"},
		%{name: "Sam Troughton", character: "Alexandr Akimov"},
		%{name: "Karl Davies", character: "Viktor Proskuryakov"},
		%{name: "Michael Socha", character: "Mikhail"},
		%{name: "Laura Elphinstone", character: "Oksana"},
		%{name: "Jan Ricica", character: "Oksana's Kid"},
		%{name: "Alan Williams", character: "KGB Chairman Charkov"},
		%{name: "Adrian Rawlins", character: "Nikolai Fomin"},
		%{name: "Con O'Neill", character: "Viktor Bryukhanov"},
		%{name: "Douggie McMeekin", character: "Yuvchenko"},
		%{name: "Nadia Clifford", character: "Dr. Svetlana Zinchenko"},
		%{name: "David Dencik", character: "Mikhail Gorbachev"},
		%{name: "Gerard Kearns", character: "Pravik"},
		%{name: "Adam Lundgren", character: "Brazhnik"}
  	],
  	description: "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.",
  	languages: ["English"],
  	countries: ["USA", "UK"],
  	poster: "https://m.media-amazon.com/images/M/MV5BNTEyYmIzMDUtNWMwNC00Y2Q1LWIyZTgtMGY1YzUxOTAwYTAwXkEyXkFqcGdeQXVyMjIyMTc0ODQ@._V1_SX300.jpg",
  	seasons: 1
  },
  %{
  	imdb_id: "tt0111999",
  	title: "Hercules: The Legendary Journeys",
  	release_date: "1995-01-16",
  	runtime: "44 min",
  	classification: "10",
  	genres: [
      %{name: "Action"},
  		%{name: "Adventure"},
  		%{name: "Drama"},
  		%{name: "Fantasy"},
  		%{name: "Romance"}
  	],
  	writers: ["Christian Williams"],
  	actors: [
  		%{name: "Kevin Sorbo", character: "Hercules", protagonist: true},
		%{name: "Michael Hurst", character: "Iolaus"},
		%{name: "Kevin Smith", character: "Ares"},
		%{name: "Robert Trebor", character: "Salmoneus"},
		%{name: "Jeffrey Thomas", character: "Jason"},
		%{name: "Paul Norell", character: "Falafel"},
		%{name: "Bruce Campbell", character: "Autolycus"},
		%{name: "Alexandra Tydings", character: "Aphrodite"},
		%{name: "Liddy Holloway", character: "Alcmene"},
		%{name: "Tamara Gorski", character: "Morrigan"},
		%{name: "Gina Torres", character: "Nebula"},
		%{name: "Joel Tobeck", character: "Strife"},
		%{name: "Lucy Lawless", character: "Xena"},
		%{name: "Meighan Desmond", character: "Discord"},
		%{name: "Lisa Chappell", character: "Dirce"},
		%{name: "Sam Sorbo", character: "Serena"},
		%{name: "Patrick Kake", character: "Hercules Double"},
		%{name: "Elizabeth Hawthorne", character: "Alcmene"},
		%{name: "Bruce Allpress", character: "Enos"},
		%{name: "Mark Nua", character: "Executioner"}
  	],
  	description: "Hercules, aided by his best friend Iolaus, goes on many adventures helping people and slaying mythical monsters using his half-god strength.",
  	languages: ["English"],
  	countries: ["USA", "New Zealand"],
  	poster: "https://m.media-amazon.com/images/M/MV5BYTUxZTM5ZWUtNzc3My00ZTAxLWFkZjEtM2FlODQ3MzI3OWRlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
  	seasons: 6,
  	spinoffs: [
	      %{imdb_id: "tt0112230", title: "Xena: Warrior Princess"},
	      %{imdb_id: "tt0169516", title: "Young Hercules"}
    	]
  },
  %{
  	imdb_id: "tt0112230",
  	title: "Xena: Warrior Princess",
  	release_date: "1995-09-04",
  	runtime: "45 min",
  	classification: "PG",
  	genres: ["Action", "Adventure", "Drama", "Fantasy"],
  	writers: [ "Sam Raimi", "John Schulian", "R.J. Stewart", "Rob Tapert"],
  	actors: [
  		%{name: "Lucy Lawless", character: "Xena", protagonist: true},
		%{name: "Renée O'Connor", character: "Gabrielle", protagonist: true},
		%{name: "Ted Raimi", character: "Joxer"},
		%{name: "Kevin Smith", character: "Ares"},
		%{name: "Hudson Leick", character: "Callisto"},
		%{name: "Karl Urban", character: "Julius Caesar"},
		%{name: "Alexandra Tydings", character: "Aphrodite"},
		%{name: "Adrienne Wilkinson", character: "Eve"},
		%{name: "Marton Csokas", character: "Borias"},
		%{name: "Danielle Cormack", character: "Ephiny"},
		%{name: "Bruce Campbell", character: "Autolycus"},
		%{name: "Darien Takle", character: "Cyrene"},
		%{name: "Charles Mesure", character: "Michael"},
		%{name: "Stephen Hall", character: "Auctioneer"},
		%{name: "Elizabeth Pendergrast", character: "Atropos"},
		%{name: "Claire Stansfield", character: "Alti"},
		%{name: "Jennifer Sky", character: "Amarice"},
		%{name: "William Gregory Lee", character: "Virgil"},
		%{name: "Willa O'Neill", character: "Lila"},
		%{name: "Timothy Omundson", character: "Eli"}
  	],
  	description: "Xena, a mighty Warrior Princess with a dark past, sets out to redeem herself. She is joined by small town bard, Gabrielle. Together they journey the ancient world and fight for the greater good against ruthless Warlords and Gods.",
  	languages: ["English"],
  	countries: ["USA", "New Zealand"],
  	poster: "https://m.media-amazon.com/images/M/MV5BOTdkYjA4YzAtMjNiZS00OTgyLTg5Y2ItNGIwZGQyMTUzNzFiXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
  	seasons: 6
  },
  %{
  	imdb_id: "tt0169516",
  	title: "Young Hercules",
  	release_date: "1998-09-12",
  	runtime: "30 min",
  	classification: "G",
  	genres: [ "Action", "Adventure", "Fantasy"],
  	writers: [ "Andrew Dettmann", "Rob Tapert", "Daniel Truly"],
  	actors: [
      	%{name: "Ryan Gosling", character: "Hercules", protagonist: true},
		%{name: "Dean O'Gorman", character: "Iolaus"},
		%{name: "Chris Conrad", character: "Jason"},
		%{name: "Jodie Rimmer", character: "Lilith"},
		%{name: "Nathaniel Lees", character: "Cheiron"},
		%{name: "Angela Marie Dotchin", character: "Kora"},
		%{name: "Kevin Smith", character: "Ares"},
		%{name: "Joel Tobeck", character: "Strife"},
		%{name: "Meighan Desmond", character: "Discord"},
		%{name: "Sharon Tyrell", character: "Alcmene"},
		%{name: "Katrina Browne", character: "Cyane"},
		%{name: "Alison Bruce", character: "Simula"},
		%{name: "Ross Duncan", character: "Fiducius"},
		%{name: "Jason Hoyte", character: "Hephaestus"},
		%{name: "Michael Daly", character: "Constable"},
		%{name: "Stephen Tozer", character: "Ophistus"},
		%{name: "Elizabeth Hawthorne", character: "Hera"},
		%{name: "Morgan Reese Fairhead", character: "Eurydice"},
		%{name: "Mfundo Morrison", character: "Theseus"},
		%{name: "Kieren Hutchison", character: "Orpheus"}
  	],
  	description: "The adventures of Hercules as a boy, during his time at a training academy for warriors.",
  	languages: ["English"],
  	countries: ["USA", "New Zealand"],
  	poster: "https://m.media-amazon.com/images/M/MV5BN2UyZGYyMTctMzA0Ny00NmE3LTg4N2QtMmM1MWNlYTdiMjQxL2ltYWdlXkEyXkFqcGdeQXVyNDUxNjc5NjY@._V1_SX300.jpg",
  	seasons: 1
  },
  %{
	imdb_id: "tt0944947",
	title: "Game of Thrones",
	release_date: "2011-04-17",
	runtime: "57 min",
	classification: "16",
	genres: ["Action", "Adventure", "Drama", "Fantasy", "Romance"],
	writers: ["David Benioff", "D.B. Weiss"],
	actors: [
		%{name: "Peter Dinklage", character: "Tyrion Lannister", protagonist: true},
		%{name: "Lena Headey", character: "Cersei Lannister"},
		%{name: "Emilia Clarke", character: "Daenerys Targaryen"},
		%{name: "Kit Harington", character: "Jon Snow"},
		%{name: "Sophie Turner", character: "Sansa Stark"},
		%{name: "Maisie Williams", character: "Arya Stark"},
		%{name: "Nikolaj Coster-Waldau", character: "Jaime Lannister"},
		%{name: "Iain Glen", character: "Jorah Mormont"},
		%{name: "John Bradley", character: "Samwell Tarly"},
		%{name: "Alfie Allen", character: "Theon Greyjoy"},
		%{name: "Conleth Hill", character: "Lord Varys"},
		%{name: "Liam Cunningham", character: "Davos Seaworth"},
		%{name: "Gwendoline Christie", character: "Brienne of Tarth"},
		%{name: "Aidan Gillen", character: "Petyr 'Littlefinger' Baelish"},
		%{name: "Isaac Hempstead Wright", character: "Bran Stark"},
		%{name: "Rory McCann", character: "Sandor 'The Hound' Clegane"},
		%{name: "Nathalie Emmanuel", character: "Missandei"},
		%{name: "Jerome Flynn", character: "Bronn"},
		%{name: "Daniel Portman", character: "Podrick Payne"},
		%{name: "Jacob Anderson", character: "Grey Worm"}
	],
	description: "Nine noble families fight for control over the mythical lands of Westeros, while an ancient enemy returns after being dormant for thousands of years.",
	languages: ["English"],
	countries: ["USA", "UK"],
	poster: "https://m.media-amazon.com/images/M/MV5BMjA5NzA5NjMwNl5BMl5BanBnXkFtZTgwNjg2OTk2NzM@._V1_SX300.jpg",
	seasons: "8"
  },
  %{
	imdb_id: "tt1475582",
	title: "Sherlock",
	release_date: "2010-10-24",
	runtime: "88 min",
	classification: "14",
	genres: ["Crime", "Drama", "Mystery", "Thriller"],
	writers: ["Mark Gatiss", "Steven Moffat"],
	actors: [
		%{name: "Benedict Cumberbatch", character: "Sherlock Holmes", protagonist: true},
		%{name: "Martin Freeman", character: "Dr. John Watson", protagonist: true},
		%{name: "Una Stubbs", character: "Mrs. Hudson"},
		%{name: "Rupert Graves", character: "DI Lestrade"},
		%{name: "Louise Brealey", character: "Molly Hooper"},
		%{name: "Mark Gatiss", character: "Mycroft Holmes"},
		%{name: "Andrew Scott", character: "Jim Moriarty"},
		%{name: "Amanda Abbington", character: "Mary Watson"},
		%{name: "Jonathan Aris", character: "Anderson"},
		%{name: "Vinette Robinson", character: "Sgt Sally Donovan"},
		%{name: "Tanya Moodie", character: "Ella"},
		%{name: "Lindsay Duncan", character: "Lady Smallwood"},
		%{name: "Yasmine Akram", character: "Janine"},
		%{name: "Sian Brooke", character: "Elizabeth"},
		%{name: "David Nellist", character: "Mike Stamford"},
		%{name: "Simon Kunz", character: "Sir Edwin"},
		%{name: "Timothy Carlton", character: "Dad"},
		%{name: "Wanda Ventham", character: "Mrs. Holmes"},
		%{name: "Lisa McAllister", character: "Anthea"},
		%{name: "Zoe Telford", character: "Sarah"}
	],
	description: "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
	languages: ["English"],
	countries: ["UK", "USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMWY3NTljMjEtYzRiMi00NWM2LTkzNjItZTVmZjE0MTdjMjJhL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTQ4NTc5OTU@._V1_SX300.jpg",
	seasons: "4"
  },
  %{
	imdb_id: "tt1632701",
	title: "Suits",
	release_date: "2011-06-23",
	runtime: "44 min",
	classification: "14",
	genres: ["Comedy", "Drama"],
	writers: ["Aaron Korsh"],
	actors: [
		%{name: "Gabriel Macht", character: "Harvey Specter", protagonist: true},
		%{name: "Rick Hoffman", character: "Louis Litt", protagonist: true},
		%{name: "Sarah Rafferty", character: "Donna Paulsen", protagonist: true},
		%{name: "Patrick J. Adams", character: "Mike Ross"},
		%{name: "Meghan Markle", character: "Rachel Zane"},
		%{name: "Gina Torres", character: "Jessica Pearson"},
		%{name: "Amanda Schull", character: "Katrina Bennett"},
		%{name: "Wendell Pierce", character: "Robert Zane"},
		%{name: "Aloma Wright", character: "Gretchen"},
		%{name: "Dulé Hill", character: "Alex Williams"},
		%{name: "Rachael Harris", character: "Sheila Sazs"},
		%{name: "Katherine Heigl", character: "Samantha Wheeler"},
		%{name: "Christina Cole", character: "Dr. Paula Agard"},
		%{name: "David Costabile", character: "Daniel Hardman"},
		%{name: "D.B. Woodside", character: "Jeff Malone"},
		%{name: "Neal McDonough", character: "Sean Cahill"},
		%{name: "Max Topplin", character: "Harold Gunderson"},
		%{name: "Abigail Spencer", character: "Dana Scott"},
		%{name: "Ray Proscia", character: "Dr. Lipschitz"},
		%{name: "John Pyper-Ferguson", character: "Jack Soloff"}
	],
	description: "On the run from a drug deal gone bad, Mike Ross, a brilliant college dropout, finds himself a job working with Harvey Specter, one of New York City's best lawyers.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BNmVmMmM5ZmItZDg0OC00NTFiLWIxNzctZjNmYTY5OTU3ZWU3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
	seasons: "8",
	spinoffs: [
	      %{imdb_id: "tt8115460", title: "Pearson"}
    	]
  },
  
  %{
	imdb_id: "tt0413573",
	title: "Grey's Anatomy",
	release_date: "2005-03-27",
	runtime: "41 min",
	classification: "14",
	genres: ["Drama", "Romance"],
	writers: ["Shonda Rhimes"],
	actors: [
		%{name: "Justin Chambers", character: "Dr. Alex Karev", protagonist: true},
		%{name: "Chandra Wilson", character: "Dr. Miranda Bailey", protagonist: true},
		%{name: "James Pickens Jr.", character: "Dr. Richard Webber", protagonist: true},
		%{name: "Ellen Pompeo", character: "Dr. Meredith Grey", protagonist: true},
		%{name: "Kevin McKidd", character: "Dr. Owen Hunt"},
		%{name: "Patrick Dempsey", character: "Dr. Derek Shepherd"},
		%{name: "Sara Ramirez", character: "Dr. Callie Torres"},
		%{name: "Bokhee An", character: "Nurse Bokhee"},
		%{name: "Jesse Williams", character: "Dr. Jackson Avery"},
		%{name: "Jessica Capshaw", character: "Dr. Arizona Robbins"},
		%{name: "Sandra Oh", character: "Dr. Cristina Yang"},
		%{name: "Sarah Drew", character: "Dr. April Kepner"},
		%{name: "Camilla Luddington", character: "Dr. Jo Wilson"},
		%{name: "Eric Dane", character: "Dr. Mark Sloan"},
		%{name: "Caterina Scorsone", character: "Dr. Amelia Shepherd"},
		%{name: "Kelly McCreary", character: "Dr. Maggie Pierce"},
		%{name: "Jason George", character: "Dr. Ben Warren"},
		%{name: "Katherine Heigl", character: "Dr. Izzie Stevens"},
		%{name: "Jerrika Hinton", character: "Dr. Stephanie Edwards"},
		%{name: "Chyler Leigh", character: "Dr. Lexie Grey"}
	],
	description: "A drama centered on the personal and professional lives of five surgical interns and their supervisors.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMTY5OTNjNTctMWYxNC00YjE2LWEzMTMtMTIzMzQ1MzhkODRhXkEyXkFqcGdeQXVyMzAzNTY3MDM@._V1_SX300.jpg",
	seasons: "15",
	spinoffs: [
	      %{imdb_id: "tt0972412", title: "Private Practice"},
		  %{imdb_id: "tt7053188", title: "Station 19"},
		  %{imdb_id: "tt8115460", title: "Pearson"}
    	]
  },
  %{
	imdb_id: "tt0108778",
	title: "Friends",
	release_date: "1994-09-22",
	runtime: "22 min",
	classification: "12",
	genres: ["Comedy", "Romance"],
	writers: ["David Crane", "Marta Kauffman"],
	actors: [
		%{name: "Jennifer Aniston", character: "Rachel Green", protagonist: true},
		%{name: "Courteney Cox", character: "Monica Geller", protagonist: true},
		%{name: "Lisa Kudrow", character: "Phoebe Buffay", protagonist: true},
		%{name: "Matt LeBlanc", character: "Joey Tribbiani", protagonist: true},
		%{name: "Matthew Perry", character: "Chandler Bing", protagonist: true},
		%{name: "David Schwimmer", character: "Dr. Ross Geller", protagonist: true},
		%{name: "James Michael Tyler", character: "Gunther"},
		%{name: "Elliott Gould", character: "Jack Geller"},
		%{name: "Christina Pickles", character: "Judy Geller"},
		%{name: "Maggie Wheeler", character: "Janice"},
		%{name: "Paul Rudd", character: "Mike Hannigan"},
		%{name: "Jane Sibbett", character: "Carol Willick"},
		%{name: "Helen Baxendale", character: "Emily Waltham"},
		%{name: "Jessica Hecht", character: "Susan Bunch"},
		%{name: "June Gable", character: "Estelle Leonard"},
		%{name: "Tom Selleck", character: "Dr. Richard Burke"},
		%{name: "Aisha Tyler", character: "Charlie Wheeler"},
		%{name: "Giovanni Ribisi", character: "Frank Buffay Jr."},
		%{name: "Lauren Tom", character: "Julie"},
		%{name: "Eddie Cahill", character: "Tag Jones"}
	],
	description: "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
	languages: ["English", "Dutch", "Italian", "French"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
	seasons: "10",
	spinoffs: [
	      %{imdb_id: "tt0375355", title: "Joey"}
    	]
  },
  %{
	imdb_id: "tt2306299",
	title: "Vikings",
	release_date: "2013-03-03",
	runtime: "44 min",
	classification: "16",
	genres: ["Action", "Adventure", "Drama", "History", "Romance", "War"],
	writers: ["Michael Hirst"],
	actors: [
		%{name: "Gustaf Skarsgård", character: "Floki", protagonist: true},
		%{name: "Katheryn Winnick", character: "Lagertha"},
		%{name: "Alexander Ludwig", character: "Bjorn Lothbrok"},
		%{name: "Travis Fimmel", character: "Ragnar Lothbrok"},
		%{name: "Clive Standen", character: "Rollo"},
		%{name: "Georgia Hirst", character: "Torvi"},
		%{name: "Alex Høgh Andersen", character: "Ivar"},
		%{name: "Jennie Jacques", character: "Judith"},
		%{name: "Maude Hirst", character: "Helga"},
		%{name: "Jordan Patrick Smith", character: "Ubbe"},
		%{name: "Moe Dunford", character: "Aethelwulf"},
		%{name: "Alyssa Sutherland", character: "Queen Aslaug"},
		%{name: "Peter Franzén", character: "King Harald Finehair"},
		%{name: "John Kavanagh", character: "The Seer"},
		%{name: "Linus Roache", character: "King Ecbert"},
		%{name: "Alicia Agneson", character: "Freydis"},
		%{name: "George Blagden", character: "Athelstan"},
		%{name: "Marco Ilsø", character: "Hvitserk"},
		%{name: "Ferdia Walsh-Peelo", character: "Alfred the Great"},
		%{name: "Jessalyn Gilsig", character: "Siggy Haraldson"}
	],
	description: "Vikings transports us to the brutal and mysterious world of Ragnar Lothbrok, a Viking warrior and farmer who yearns to explore - and raid - the distant shores across the ocean.",
	languages: ["English", "Old English", "Norse", " Old", "Latin", "French"],
	countries: ["Ireland", "Canada"],
	poster: "https://m.media-amazon.com/images/M/MV5BNDYyNzk1NzYwOF5BMl5BanBnXkFtZTgwMTQ0Nzc4MzI@._V1_SX300.jpg",
	seasons: "5"
  },
  %{
	imdb_id: "tt3205802",
	title: "How to Get Away with Murder",
	release_date: "2014-09-25",
	runtime: "43 min",
	classification: "14",
	genres: ["Crime", "Drama", "Mystery", "Thriller"],
	writers: ["Peter Nowalk"],
	actors: [
		%{name: "Viola Davis", character: "Annalise Keating", protagonist: true},
		%{name: "Billy Brown", character: "Nate Lahey", protagonist: true},
		%{name: "Jack Falahee", character: "Connor Walsh", protagonist: true},
		%{name: "Aja Naomi King", character: "Michaela Pratt", protagonist: true},
		%{name: "Matt McGorry", character: "Asher Millstone", protagonist: true},
		%{name: "Karla Souza", character: "Laurel Castillo", protagonist: true},
		%{name: "Charlie Weber", character: "Frank Delfino", protagonist: true},
		%{name: "Liza Weil", character: "Bonnie Winterbottom", protagonist: true},
		%{name: "Conrad Ricamora", character: "Oliver Hampton"},
		%{name: "Alfred Enoch", character: "Wes Gibbins"},
		%{name: "Amirah Vann", character: "Tegan Price"},
		%{name: "Behzad Dabu", character: "Simon Drake"},
		%{name: "Tom Verica", character: "Sam Keating"},
		%{name: "Benito Martinez", character: "A.D.A. Todd Denver"},
		%{name: "Rome Flynn", character: "Gabriel Maddox"},
		%{name: "Katie Findlay", character: "Rebecca Sutter"},
		%{name: "Timothy Hutton", character: "Emmett Crawford"},
		%{name: "Jasmyne Jones", character: "Baby Christopher"},
		%{name: "Adrianna Jones", character: "Baby Christopher"},
		%{name: "John Hensley", character: "Interim D.A. Ronald Miller"}
	],
	description: "A group of ambitious law students and their brilliant criminal defense professor become involved in a twisted murder plot that promises to change the course of their lives.",
	languages: ["English", "Spanish"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMjMzNzM1MDI4NV5BMl5BanBnXkFtZTgwNjk1OTYzNjM@._V1_SX300.jpg",
	seasons: "5"
  },
  %{
	imdb_id: "tt0455275",
	title: "Prison Break",
	release_date: "2005-08-29",
	runtime: "44 min",
	classification: "16",
	genres: ["Action", "Crime", "Drama", "Mystery", "Thriller"],
	writers: ["Paul Scheuring"],
	actors: [
		%{name: "Dominic Purcell", character: "Lincoln 'Linc' Burrows", protagonist: true},
		%{name: "Wentworth Miller", character: "Michael Scofield", protagonist: true},
		%{name: "Robert Knepper", character: "Theodore 'T-Bag' Bagwell"},
		%{name: "Amaury Nolasco", character: "Fernando Sucre"},
		%{name: "Sarah Wayne Callies", character: "Sara Tancredi"},
		%{name: "Wade Williams", character: "Brad Bellick"},
		%{name: "William Fichtner", character: "Alexander 'Alex' Mahone"},
		%{name: "Paul Adelstein", character: "Paul Kellerman"},
		%{name: "Rockmond Dunbar", character: "Benjamin Miles 'C-Note' Franklin"},
		%{name: "Jodi Lyn O'Keefe", character: "Gretchen Morgan"},
		%{name: "Leon Russom", character: "General Jonathan Krantz"},
		%{name: "Marshall Allman", character: "LJ Burrows"},
		%{name: "Robin Tunney", character: "Veronica Donovan"},
		%{name: "Stacy Keach", character: "Warden Henry Pope"},
		%{name: "Michael Rapaport", character: "Don Self"},
		%{name: "Peter Stormare", character: "John Abruzzi"},
		%{name: "Phillip Edward Van Lear", character: "Louis Patterson"},
		%{name: "Muse Watson", character: "Charles Westmoreland"},
		%{name: "Barbara Eve Harris", character: "FBI Agent Felicia Lang"},
		%{name: "Frank Grillo", character: "Nick Savrinn"}
	],
	description: "Due to a political conspiracy, an innocent man is sent to death row and his only hope is his brother, who makes it his mission to deliberately get himself sent to the same prison in order to break the both of them out, from the inside.",
	languages: ["Spanish", "English"],
	countries: ["UK", "USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMTg3NTkwNzAxOF5BMl5BanBnXkFtZTcwMjM1NjI5MQ@@._V1_SX300.jpg",
	seasons: "5"
  },
  %{
	imdb_id: "tt3322312",
	title: "Daredevil",
	release_date: "2015-04-10",
	runtime: "54 min",
	classification: "18",
	genres: ["Action", "Crime", "Drama", "Fantasy", "Sci-Fi", "Thriller"],
	writers: ["Drew Goddard"],
	actors: [
		%{name: "Charlie Cox", character: "Matt Murdock", protagonist: true},
		%{name: "Deborah Ann Woll", character: "Karen Page", protagonist: true},
		%{name: "Elden Henson", character: "Foggy Nelson"},
		%{name: "Vincent D'Onofrio", character: "Wilson Fisk"},
		%{name: "Royce Johnson", character: "Brett Mahoney"},
		%{name: "Geoffrey Cantor", character: "Mitchell Ellison"},
		%{name: "Jay Ali", character: "Ray Nadeem"},
		%{name: "Jon Bernthal", character: "Frank Castle"},
		%{name: "Stephen Rider", character: "Blake Tower"},
		%{name: "Wilson Bethel", character: "Benjamin 'Dex' Poindexter"},
		%{name: "Ayelet Zurer", character: "Vanessa Marianna"},
		%{name: "Peter McRobbie", character: "Father Lantom"},
		%{name: "Amy Rutberg", character: "Marci Stahl"},
		%{name: "Elodie Yung", character: "Elektra Natchios"},
		%{name: "Toby Leonard Moore", character: "James Wesley"},
		%{name: "Joanne Whalley", character: "Sister Maggie"},
		%{name: "Vondie Curtis-Hall", character: "Ben Urich"},
		%{name: "Bob Gunton", character: "Leland Owlsley"},
		%{name: "Kate Udall", character: "SAC Tammy Hattley"},
		%{name: "Susan Varon", character: "Josie"}
	],
	description: "A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BODcwOTg2MDE3NF5BMl5BanBnXkFtZTgwNTUyNTY1NjM@._V1_SX300.jpg",
	seasons: "3"
  },
  %{
	imdb_id: "tt0460649",
	title: "How I Met Your Mother",
	release_date: "2005-09-19",
	runtime: "22 min",
	classification: "12",
	genres: ["Comedy", "Romance"],
	writers: ["Carter Bays", "Craig Thomas"],
	actors: [
		%{name: "Josh Radnor", character: "Ted Mosby", protagonist: true},
		%{name: "Jason Segel", character: "Marshall Eriksen", protagonist: true},
		%{name: "Cobie Smulders", character: "Robin Scherbatsky", protagonist: true},
		%{name: "Neil Patrick Harris", character: "Barney Stinson", protagonist: true},
		%{name: "Alyson Hannigan", character: "Lily Aldrin", protagonist: true},
		%{name: "Lyndsy Fonseca", character: "Daughter"},
		%{name: "David Henrie", character: "Son"},
		%{name: "Cristin Milioti", character: "Tracy McConnell"},
		%{name: "Marshall Manesh", character: "Ranjit"},
		%{name: "Joe Nieves", character: "Carl"},
		%{name: "Charlene Amoia", character: "Wendy"},
		%{name: "Ashley Williams", character: "Victoria"},
		%{name: "Suzie Plakson", character: "Judy"},
		%{name: "Jennifer Morrison", character: "Zoey"},
		%{name: "Wayne Brady", character: "James"},
		%{name: "Bill Fagerbakke", character: "Marvin Sr."},
		%{name: "Ellen D. Williams", character: "Patrice"},
		%{name: "Chris Elliott", character: "Mickey"},
		%{name: "Robert Belushi", character: "Linus"},
		%{name: "Ned Rolsma", character: "Marcus"}
	],
	description: "A father recounts to his children, through a series of flashbacks, the journey he and his four best friends took leading up to him meeting their mother.",
	languages: ["English", "Persian", "Chinese"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BZWJjMDEzZjUtYWE1Yy00M2ZiLThlMmItODljNTAzODFiMzc2XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
	seasons: "9"
  },
  %{
	imdb_id: "tt0412142",
	title: "House",
	release_date: "2004-09-16",
	runtime: "44 min",
	classification: "14",
	genres: ["Drama", "Mystery"],
	writers: ["David Shore"],
	actors: [
		%{name: "Hugh Laurie", character: "Dr. Gregory House", protagonist: true},
		%{name: "Omar Epps", character: "Dr. Eric Foreman"},
		%{name: "Robert Sean Leonard", character: "Dr. James Wilson"},
		%{name: "Jesse Spencer", character: "Dr. Robert Chase"},
		%{name: "Lisa Edelstein", character: "Dr. Lisa Cuddy"},
		%{name: "Bobbin Bergstrom", character: "Nurse"},
		%{name: "Jennifer Morrison", character: "Dr. Allison Cameron"},
		%{name: "Peter Jacobson", character: "Dr. Chris Taub"},
		%{name: "Olivia Wilde", character: "Dr. Remy 'Thirteen' Hadley"},
		%{name: "Kal Penn", character: "Dr. Lawrence Kutner"},
		%{name: "Odette Annable", character: "Dr. Jessica Adams"},
		%{name: "Charlyne Yi", character: "Dr. Chi Park"},
		%{name: "Anne Dudek", character: "Dr. Amber Volakis"},
		%{name: "Jennifer Crystal Foley", character: "Rachel Taub"},
		%{name: "Amber Tamblyn", character: "Martha M. Masters"},
		%{name: "Liz Benoit", character: "Nurse Anne"},
		%{name: "Stephanie Venditto", character: "Nurse Brenda Previn"},
		%{name: "Sela Ward", character: "Stacy Warner"},
		%{name: "Michael Weston", character: "Lucas Douglas"},
		%{name: "Ron Perkins", character: "Dr. Ron Simpson"}
	],
	description: "An antisocial maverick doctor who specializes in diagnostic medicine does whatever it takes to solve puzzling cases that come his way using his crack team of doctors and his wits.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMDA4NjQzN2ItZDhhNC00ZjVlLWFjNTgtMTEyNDQyOGNjMDE1XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
	seasons: "8"
  },
  %{
	imdb_id: "tt1856010",
	title: "House of Cards",
	release_date: "2013-02-01",
	runtime: "51 min",
	classification: "16",
	genres: ["Drama"],
	writers: ["Beau Willimon"],
	actors: [
		%{name: "Robin Wright", character: "Claire Underwood", protagonist: true},
		%{name: "Michael Kelly", character: "Doug Stamper"},
		%{name: "Kevin Spacey", character: "Francis Underwood"},
		%{name: "Justin Doescher", character: "Frank Underwood Security"},
		%{name: "Derek Cecil", character: "Seth Grayson"},
		%{name: "Jayne Atkinson", character: "Catherine Durant"},
		%{name: "Nathan Darrow", character: "Edward Meechum"},
		%{name: "Mahershala Ali", character: "Remy Danton"},
		%{name: "Boris McGiver", character: "Tom Hammerschmidt"},
		%{name: "Paul Sparks", character: "Thomas Yates"},
		%{name: "Gary Ayash", character: "White House Press Corp Reporter"},
		%{name: "Jeremy Holm", character: "Nathan Green"},
		%{name: "Molly Parker", character: "Jackie Sharp"},
		%{name: "Neve Campbell", character: "Leann Harvey"},
		%{name: "Michel Gill", character: "President Garrett Walker"},
		%{name: "Marla Aaron Wapner", character: "WH Press Corp"},
		%{name: "Nini Le Huynh", character: "Claire's Assistant"},
		%{name: "Dave Ferrier", character: "Videographer"},
		%{name: "Elizabeth Marvel", character: "Heather Dunbar"},
		%{name: "Larry Pine", character: "Bob Birch"}
	],
	description: "A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BNmM4ODU1MzItODYyYi00Y2U0LWFjZjItYTRhZWIwOGMyZTRhXkEyXkFqcGdeQXVyNjc2NTQ4Nzk@._V1_SX300.jpg",
	seasons: "6"
  },
  %{
	imdb_id: "tt1124373",
	title: "Sons of Anarchy",
	release_date: "2008-09-03",
	runtime: "45 min",
	classification: "16",
	genres: ["Crime", "Drama", "Thriller"],
	writers: ["Kurt Sutter"],
	actors: [
		%{name: "Charlie Hunnam", character: "Jackson 'Jax' Teller", protagonist: true},
		%{name: "Katey Sagal", character: "Gemma Teller Morrow", protagonist: true},
		%{name: "Mark Boone Junior", character: "Robert 'Bobby Elvis' Munson", protagonist: true},
		%{name: "Kim Coates", character: "Alexander 'Tig' Trager", protagonist: true},
		%{name: "Tommy Flanagan", character: "Filip 'Chibs' Telford", protagonist: true},
		%{name: "Theo Rossi", character: "Juan Carlos 'Juice' Ortiz"},
		%{name: "Dayton Callie", character: "Wayne Unser"},
		%{name: "Maggie Siff", character: "Dr. Tara Knowles"},
		%{name: "Ron Perlman", character: "Clarence 'Clay' Morrow"},
		%{name: "David Labrava", character: "Happy Lowman"},
		%{name: "Ryan Hurst", character: "Harry 'Opie' Winston"},
		%{name: "William Lucking", character: "Piermont 'Piney' Winston"},
		%{name: "Michael Ornstein", character: "Chuck 'Chucky' Marstein"},
		%{name: "Winter Ave Zoli", character: "Lyla Winston"},
		%{name: "Jimmy Smits", character: "Nero Padilla"},
		%{name: "Niko Nicotera", character: "George 'Ratboy' Skogstrom"},
		%{name: "Chris Reed", character: "Philip 'Filthy Phil' Russell"},
		%{name: "Drea de Matteo", character: "Wendy Case"},
		%{name: "Emilio Rivera", character: "Marcus Alvarez"},
		%{name: "Rockmond Dunbar", character: "Lieutenant Eli Roosevelt"}
	],
	description: "A biker struggles to balance being a father and being involved in an outlaw motorcycle club.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMTEyODg2NzkwMDBeQTJeQWpwZ15BbWU4MDQwODI3MzIx._V1_SX300.jpg",
	seasons: "7"
  },
  
  %{
	imdb_id: "tt2632424",
	title: "The Originals",
	release_date: "2013-10-03",
	runtime: "45 min",
	classification: "16",
	genres: ["Drama", "Fantasy", "Horror", "Mystery"],
	writers: ["Julie Plec"],
	actors: [
		%{name: "Joseph Morgan", character: "Klaus Mikaelson", protagonist: true},
		%{name: "Daniel Gillies", character: "Elijah Mikaelson", protagonist: true},
		%{name: "Charles Michael Davis", character: "Marcel Gerard", protagonist: true},
		%{name: "Phoebe Tonkin", character: "Hayley Marshall"},
		%{name: "Yusuf Gatewood", character: "Vincent Griffith"},
		%{name: "Danielle Campbell", character: "Davina Claire"},
		%{name: "Leah Pipes", character: "Camille O'Connell"},
		%{name: "Riley Voelkel", character: "Freya Mikaelson"},
		%{name: "Steven Krueger", character: "Josh Rosza"},
		%{name: "Claire Holt", character: "Rebekah Mikaelson"},
		%{name: "Nathan Parsons", character: "Jackson Kenner"},
		%{name: "Nathaniel Buzolic", character: "Kol Mikaelson"},
		%{name: "Sebastian Roché", character: "Mikael"},
		%{name: "Christina Moses", character: "Keelin"},
		%{name: "Maisie Richardson-Sellers", character: "Eva Sinclair"},
		%{name: "Andrew Lees", character: "Lucien Castle"},
		%{name: "Colin Woodell", character: "Aiden"},
		%{name: "Rebecca Breeds", character: "Aurora de Martel"},
		%{name: "Daniella Pineda", character: "Sophie Deveraux"},
		%{name: "Danielle Rose Russell", character: "Hope Mikaelson"}
	],
	description: "A family of power-hungry thousand year old vampires look to take back the city that they built and dominate all those who have done them wrong.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BNDllZjc2NjEtOGMwZS00ZmNkLTg2NDgtZjJkYjg0YjMxM2FmXkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_SX300.jpg",
	seasons: "5"
  },
  %{
	imdb_id: "tt1520211",
	title: "The Walking Dead",
	release_date: "2010-10-31",
	runtime: "44 min",
	classification: "16",
	genres: ["Drama", "Horror", "Thriller"],
	writers: ["Frank Darabont", "Angela Kang"],
	actors: [
		%{name: "Norman Reedus", character: "Daryl Dixon", protagonist: true},
		%{name: "Melissa McBride", character: "Carol Peletier", protagonist: true},
		%{name: "Andrew Lincoln", character: "Rick Grimes", protagonist: true},
		%{name: "Danai Gurira", character: "Michonne"},
		%{name: "Lauren Cohan", character: "Maggie Greene"},
		%{name: "Chandler Riggs", character: "Carl Grimes"},
		%{name: "Josh McDermitt", character: "Eugene Porter"},
		%{name: "Christian Serratos", character: "Rosita Espinosa"},
		%{name: "Alanna Masterson", character: "Tara Chambler"},
		%{name: "Seth Gilliam", character: "Gabriel Stokes"},
		%{name: "Steven Yeun", character: "Glenn Rhee"},
		%{name: "Ross Marquand", character: "Aaron"},
		%{name: "Sonequa Martin-Green", character: "Sasha Williams"},
		%{name: "Jeffrey Dean Morgan", character: "Negan"},
		%{name: "Lennie James", character: "Morgan Jones"},
		%{name: "Emily Kinney", character: "Beth Greene"},
		%{name: "Katelyn Nacon", character: "Enid"},
		%{name: "Tom Payne", character: "Paul 'Jesus' Rovia"},
		%{name: "Khary Payton", character: "Ezekiel"},
		%{name: "Michael Cudlitz", character: "Abraham Ford"}
	],
	description: "Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins, and must lead a group of survivors to stay alive.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BYWY4ODJiZjMtNWMxYi00ZmM5LWIwZmQtZWY0MjJmZGU5MjcxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
	seasons: "9"
  },
  %{
	imdb_id: "tt3006802",
	title: "Outlander",
	release_date: "2014-08-09",
	runtime: "64 min",
	classification: "16",
	genres: ["Drama", "Fantasy", "Romance"],
	writers: ["Ronald D. Moore"],
	actors: [
		%{name: "Caitriona Balfe", character: "Claire Randall", protagonist: true},
		%{name: "Sam Heughan", character: "Jamie Fraser", protagonist: true},
		%{name: "Duncan Lacroix", character: "Murtagh Fraser"},
		%{name: "Tobias Menzies", character: "Frank Randall"},
		%{name: "Grant O'Rourke", character: "Rupert MacKenzie"},
		%{name: "Graham McTavish", character: "Dougal MacKenzie"},
		%{name: "Stephen Walters", character: "Angus Mhor"},
		%{name: "John Bell", character: "Young Ian"},
		%{name: "Sophie Skelton", character: "Brianna Randall Fraser"},
		%{name: "Richard Rankin", character: "Roger Wakefield"},
		%{name: "César Domboy", character: "Fergus"},
		%{name: "Romann Berrux", character: "Fergus"},
		%{name: "Lauren Lyle", character: "Marsali"},
		%{name: "Andrew Gower", character: "Prince Charles Edward Stuart"},
		%{name: "Steven Cree", character: "Ian Murray"},
		%{name: "Keith Fleming", character: "Lesley"},
		%{name: "James Allenby-Kirk", character: "Hayes"},
		%{name: "Nell Hudson", character: "Laoghaire MacKenzie"},
		%{name: "Lotte Verbeek", character: "Geillis Duncan"},
		%{name: "Laura Donnelly", character: "Jenny Fraser"}
	],
	description: "An English combat nurse from 1945 is mysteriously swept back in time to 1743.",
	languages: ["English", "Scottish Gaelic"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMTU1NDc3NzYxN15BMl5BanBnXkFtZTgwMTgyMjQyNjM@._V1_SX300.jpg",
	seasons: "6"
  },
  %{
	imdb_id: "tt3107288",
	title: "The Flash",
	release_date: "2014-10-07",
	runtime: "43 min",
	classification: "12",
	genres: ["Action", "Adventure", "Drama", "Sci-Fi"],
	writers: ["Greg Berlanti", "Geoff Johns", "Andrew Kreisberg"],
	actors: [
		%{name: "Grant Gustin", character: "Barry Allen", protagonist: true},
		%{name: "Candice Patton", character: "Iris West", protagonist: true},
		%{name: "Danielle Panabaker", character: "Caitlin Snow", protagonist: true},
		%{name: "Carlos Valdes", character: "Cisco Ramon", protagonist: true},
		%{name: "Tom Cavanagh", character: "Dr. Harry Wells"},
		%{name: "Jesse L. Martin", character: "Joe West"},
		%{name: "Keiynan Lonsdale", character: "Wally West"},
		%{name: "Danielle Nicolet", character: "Cecille Horton"},
		%{name: "Patrick Sabongui", character: "Captain David Singh"},
		%{name: "Hartley Sawyer", character: "Ralph Dibny"},
		%{name: "Rick Cosnett", character: "Detective Eddie Thawne"},
		%{name: "Jessica Parker Kennedy", character: "Nora West-Allen"},
		%{name: "Violett Beane", character: "Jesse Wells"},
		%{name: "John Wesley Shipp", character: "Henry Allen"},
		%{name: "Teddy Sears", character: "Jay Garrick"},
		%{name: "Tom Felton", character: "Julian Albert"},
		%{name: "Chris Klein", character: "Orlin Dwyer"},
		%{name: "Kim Engelbrecht", character: "The Mechanic"},
		%{name: "Tony Todd", character: "Zoom"},
		%{name: "Neil Sandilands", character: "The Thinker"}
	],
	description: "After being struck by lightning, Barry Allen wakes up from his coma to discover he's been given the power of super speed, becoming the Flash, fighting crime in Central City.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMjI1MDAwNDM4OV5BMl5BanBnXkFtZTgwNjUwNDIxNjM@._V1_SX300.jpg",
	seasons: "6"
  },
  %{
	imdb_id: "tt1567432",
	title: "Teen Wolf",
	release_date: "2011-06-05",
	runtime: "41 min",
	classification: "12",
	genres: ["Action", "Drama", "Fantasy", "Romance", "Thriller"],
	writers: ["Jeff Davis"],
	actors: [
		%{name: "Tyler Posey", character: "Scott McCall", protagonist: true},
		%{name: "Holland Roden", character: "Lydia Martin", protagonist: true},
		%{name: "Dylan O'Brien", character: "Stiles Stilinski"},
		%{name: "Linden Ashby", character: "Sheriff Noah Stilinski"},
		%{name: "JR Bourne", character: "Chris Argent"},
		%{name: "Melissa Ponzio", character: "Melissa McCall"},
		%{name: "Tyler Hoechlin", character: "Derek Hale"},
		%{name: "Shelley Hennig", character: "Malia Tate"},
		%{name: "Dylan Sprayberry", character: "Liam Dunbar"},
		%{name: "Crystal Reed", character: "Allison Argent"},
		%{name: "Ryan Kelley", character: "Deputy Jordan Parrish"},
		%{name: "Arden Cho", character: "Kira Yukimura"},
		%{name: "Seth Gilliam", character: "Dr. Alan Deaton"},
		%{name: "Ian Bohen", character: "Peter Hale"},
		%{name: "Khylin Rhambo", character: "Mason Hewitt"},
		%{name: "Orny Adams", character: "Coach Bobby Finstock"},
		%{name: "Daniel Sharman", character: "Isaac Lahey"},
		%{name: "Cody Christian", character: "Theo Raeken"},
		%{name: "Michael Johnston", character: "Corey"},
		%{name: "Keahu Kahuanui", character: "Danny Mahealani"}
	],
	description: "An average high school student and his best friend get caught up in some trouble causing him to receive a werewolf bite. As a result they find themselves in the middle of all sorts of dramas in Beacon Hills.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMThlNTk3YzMtOTZjMi00M2NiLTg1NTgtYThiYzE2MDFmMDUwXkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_SX300.jpg",
	seasons: "6"
  },
  %{
	imdb_id: "tt0436992",
	title: "Doctor Who",
	release_date: "2006-03-17",
	runtime: "45 min",
	classification: "10",
	genres: ["Adventure", "Drama", "Family", "Mystery", "Sci-Fi"],
	writers: ["Sydney Newman"],
	actors: [
		%{name: "Matt Smith", character: "The Doctor", protagonist: true},
		%{name: "David Tennant", character: "The Doctor", protagonist: true},
		%{name: "Peter Capaldi", character: "The Doctor", protagonist: true},
		%{name: "Nicholas Briggs", character: "Daleks"},
		%{name: "Jenna Coleman", character: "Clara"},
		%{name: "Karen Gillan", character: "Amy Pond"},
		%{name: "Paul Kasey", character: "Ood Sigma"},
		%{name: "Billie Piper", character: "Rose Tyler"},
		%{name: "Arthur Darvill", character: "Rory"},
		%{name: "Jodie Whittaker", character: "The Doctor"},
		%{name: "Ruari Mears", character: "Cyberman"},
		%{name: "Bradley Walsh", character: "Graham O'Brien"},
		%{name: "Tosin Cole", character: "Ryan Sinclair"},
		%{name: "Mandip Gill", character: "Yasmin Khan"},
		%{name: "Freema Agyeman", character: "Martha Jones"},
		%{name: "Barnaby Edwards", character: "Dalek Operator"},
		%{name: "Catherine Tate", character: "Donna Noble"},
		%{name: "Alex Kingston", character: "River Song"},
		%{name: "Matt Lucas", character: "Nardole"},
		%{name: "Camille Coduri", character: "Jackie Tyler"}
	],
	description: "The further adventures in time and space of the alien adventurer known as the Doctor and their companions from planet Earth.",
	languages: ["English"],
	countries: ["UK", "Canada"],
	poster: "https://m.media-amazon.com/images/M/MV5BNDY1YmZhZjEtY2E3NC00M2VkLThlZmUtODczMmNiZjMxMWRhXkEyXkFqcGdeQXVyNzA5NTYxMDg@._V1_SX300.jpg",
	seasons: "12"
  },
  %{
	imdb_id: "tt0475784",
	title: "Westworld",
	release_date: "2016-10-02",
	runtime: "62 min",
	classification: "16",
	genres: ["Drama", "Mystery", "Sci-Fi", "Western"],
	writers: ["N/A"],
	actors: [
		%{name: "Evan Rachel Wood", character: "Dolores Abernathy", protagonist: true},
		%{name: "Jeffrey Wright", character: "Bernard Lowe", protagonist: true},
		%{name: "Ed Harris", character: "Man in Black", protagonist: true},
		%{name: "Tessa Thompson", character: "Charlotte Hale"},
		%{name: "Thandie Newton", character: "Maeve Millay"},
		%{name: "James Marsden", character: "Teddy Flood"},
		%{name: "Anthony Hopkins", character: "Dr. Robert Ford"},
		%{name: "Angela Sarafyan", character: "Clementine Pennyfeather"},
		%{name: "Luke Hemsworth", character: "Ashley Stubbs"},
		%{name: "Simon Quarterman", character: "Lee Sizemore"},
		%{name: "Shannon Woodward", character: "Elsie Hughes"},
		%{name: "Rodrigo Santoro", character: "Hector Escaton"},
		%{name: "Talulah Riley", character: "Angela"},
		%{name: "Ptolemy Slocum", character: "Sylvester"},
		%{name: "Leonardo Nam", character: "Lutz"},
		%{name: "Ingrid Bolsø Berdal", character: "Armistice"},
		%{name: "Ben Barnes", character: "Logan"},
		%{name: "Jimmi Simpson", character: "William"},
		%{name: "Louis Herthum", character: "Peter Abernathy"},
		%{name: "Jasmyn Rae", character: "Maeve's Daughter"}
	],
	description: "Set at the intersection of the near future and the reimagined past, explore a world in which every human appetite can be indulged without consequence.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BNThjM2Y3MDUtYTIyNC00ZDliLWJlMmItNWY1N2E5NjhmMGM4XkEyXkFqcGdeQXVyNjU2ODM5MjU@._V1_SX300.jpg",
	seasons: "3"
  },
  %{
	imdb_id: "tt0898266",
	title: "The Big Bang Theory",
	release_date: "2006-05-01",
	runtime: "22 min",
	classification: "10",
	genres: ["Comedy", "Romance"],
	writers: ["Chuck Lorre", "Bill Prady"],
	actors: [
		%{name: "Johnny Galecki", character: "Leonard Hofstadter", protagonist: true},
		%{name: "Jim Parsons", character: "Sheldon Cooper", protagonist: true},
		%{name: "Kaley Cuoco", character: "Penny", protagonist: true},
		%{name: "Simon Helberg", character: "Howard Wolowitz", protagonist: true},
		%{name: "Kunal Nayyar", character: "Raj Koothrappali", protagonist: true},
		%{name: "Melissa Rauch", character: "Bernadette Rostenkowski"},
		%{name: "Mayim Bialik", character: "Amy Farrah Fowler"},
		%{name: "Kevin Sussman", character: "Stuart Bloom"},
		%{name: "Carol Ann Susi", character: "Debbie Wolowitz"},
		%{name: "John Ross Bowie", character: "Barry Kripke"},
		%{name: "Laura Spencer", character: "Emily Sweeney"},
		%{name: "Wil Wheaton", character: "Wil Wheaton"},
		%{name: "Brian George", character: "Dr. V.M. Koothrappali"},
		%{name: "Christine Baranski", character: "Dr. Beverly Hofstadter"},
		%{name: "Brian Posehn", character: "Bert Kibbler"},
		%{name: "Laurie Metcalf", character: "Mary Cooper"},
		%{name: "Joshua Malina", character: "President Siebert"},
		%{name: "Aarti Mann", character: "Priya Koothrappali"},
		%{name: "Ian Scott Rudolph", character: "Captain Sweatpants"},
		%{name: "Brian Thomas Smith", character: "Zack Johnson"}
	],
	description: "A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.",
	languages: ["Klingon", "English", "Hindi", "Italian", "Russian", "Mandarin"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BY2FmZTY5YTktOWRlYy00NmIyLWE0ZmQtZDg2YjlmMzczZDZiXkEyXkFqcGdeQXVyNjg4NzAyOTA@._V1_SX300.jpg",
	seasons: "12"
  },
  %{
	imdb_id: "tt0460637",
	title: "Everybody Hates Chris",
	release_date: "2005-09-22",
	runtime: "22 min",
	classification: "14",
	genres: ["Comedy"],
	writers: ["Ali LeRoi", "Chris Rock"],
	actors: [
		%{name: "Terry Crews", character: "Julius", protagonist: true},
		%{name: "Tichina Arnold", character: "Rochelle", protagonist: true},
		%{name: "Tequan Richmond", character: "Drew", protagonist: true},
		%{name: "Imani Hakim", character: "Tonya", protagonist: true},
		%{name: "Vincent Martella", character: "Greg Wuliger", protagonist: true},
		%{name: "Tyler James Williams", character: "Chris", protagonist: true},
		%{name: "Chris Rock", character: "Narrator", protagonist: true},
		%{name: "Travis T. Flory", character: "Joey Caruso"},
		%{name: "Jacqueline Mazarella", character: "Ms. Morello"},
		%{name: "Kevontay Jackson", character: "Jerome"},
		%{name: "Ernest Thomas", character: "Mr. Omar"},
		%{name: "Jeris Poindexter", character: "Kill Moves"},
		%{name: "Michel Estime", character: "Risky"},
		%{name: "Antonio Fargas", character: "Doc"},
		%{name: "Jackée Harry", character: "Vanessa"},
		%{name: "Blake Hightower", character: "James"},
		%{name: "Todd Bridges", character: "Monk"},
		%{name: "Paige Hurd", character: "Tasha"},
		%{name: "Owen H.M. Smith", character: "Bouncer"},
		%{name: "Shon Little", character: "Cop"}
	],
	description: "A young African American teen attempts to survive with his dysfunctional family and his all white school in the 1980s.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMTU2NTg4MTc5OF5BMl5BanBnXkFtZTcwMzc2MzYzMQ@@._V1_SX300.jpg",
	seasons: "4"
  },
  %{
	imdb_id: "tt8115460",
	title: "Pearson",
	release_date: "2019-07-17",
	runtime: "60 min",
	classification: "14",
	genres: ["Drama"],
	writers: ["Daniel Arkin", "Aaron Korsh"],
	actors: [
		%{name: "Gina Torres", character: "Jessica Pearson", protagonist: true},
		%{name: "Bethany Joy Lenz", character: "Keri Allen", protagonist: true},
		%{name: "Simon Kassianides", character: "Nick D'Amato", protagonist: true},
		%{name: "Eli Goree", character: "Derrick Mayes", protagonist: true},
		%{name: "Isabel Arraiza", character: "Yoli Castillo"},
		%{name: "Chantel Riley", character: "Angela Cook"},
		%{name: "Morgan Spector", character: "Mayor Bobby Novak"},
		%{name: "Wayne Duvall", character: "Pat McGann"},
		%{name: "Jonny Berryman", character: "Cory"},
		%{name: "Ethan Ireland", character: "Mark"},
		%{name: "Juanita Jennings", character: "Lillian Cook"},
		%{name: "D.B. Woodside", character: "Jeff Malone"},
		%{name: "Danni DanDan Gadigan", character: "City Clerk"},
		%{name: "Betsy Brandt", character: "Stephanie Novak"},
		%{name: "Brandon Young", character: "Malik"},
		%{name: "Mat Devine", character: "Luke"},
		%{name: "Colby French", character: "Frank Cramer"},
		%{name: "Jim O'Heir", character: "Police Superintendent Chuck Hargrove"},
		%{name: "Ivan Shaw", character: "Albert Chan"},
		%{name: "Javier Lezama", character: "Oscar"}
	],
	description: "Attorney Jessica Pearson enters the complex and seedy world of Chicago politics.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMTU3YWUyNjYtNDBkYi00MGU0LTk0OWYtZTc3MjEwOTllZGFjXkEyXkFqcGdeQXVyOTUyNjcyNA@@._V1_SX300.jpg",
	seasons: "N/A"
  },
  
  %{
	imdb_id: "tt0972412",
	title: "Private Practice",
	release_date: "2007-09-19",
	runtime: "60 min",
	classification: "14",
	genres: ["Comedy", "Drama", "Romance"],
	writers: ["Shonda Rhimes"],
	actors: [
		%{name: "Kate Walsh", character: "Dr. Addison Forbes Montgomery", protagonist: true},
		%{name: "Paul Adelstein", character: "Dr. Cooper Freedman", protagonist: true},
		%{name: "KaDee Strickland", character: "Dr. Charlotte King", protagonist: true},
		%{name: "Taye Diggs", character: "Dr. Sam Bennett", protagonist: true},
		%{name: "Amy Brenneman", character: "Dr. Violet Turner", protagonist: true},
		%{name: "Tim Daly", character: "Dr. Pete Wilder"},
		%{name: "Brian Benben", character: "Dr. Sheldon Wallace"},
		%{name: "Audra McDonald", character: "Dr. Naomi Bennett"},
		%{name: "Caterina Scorsone", character: "Dr. Amelia Shepherd"},
		%{name: "Chris Lowell", character: "William 'Dell' Parker"},
		%{name: "Benjamin Bratt", character: "Dr. Jake Reilly"},
		%{name: "Griffin Gluck", character: "Mason Warner"},
		%{name: "Scott Alan Smith", character: "Therapist"},
		%{name: "Jack Bobo", character: "Lucas"},
		%{name: "Joey Bobo", character: "Lucas"},
		%{name: "A.J. Langer", character: "Erica Warner"},
		%{name: "Michael Patrick Thornton", character: "Dr. Gabriel Fife"},
		%{name: "David Sutcliffe", character: "Officer Kevin Nelson"},
		%{name: "GeffriMaya", character: "Maya Bennett"},
		%{name: "Hailey Sole", character: "Betsey"}
	],
	description: "A spin-off of the medical drama \"Grey's Anatomy\" centering on the life of neonatal surgeon Addison Montgomery.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMjQ4MjE1NzU5Nl5BMl5BanBnXkFtZTgwOTIwMzg5NjE@._V1_SX300.jpg",
	seasons: "6"
  },
  %{
	imdb_id: "tt7053188",
	title: "Station 19",
	release_date: "2018-03-22",
	runtime: "60 min",
	classification: "14",
	genres: ["Action", "Drama", "Romance", "Thriller"],
	writers: ["Stacy McKee"],
	actors: [
		%{name: "Jaina Lee Ortiz", character: "Andy Herrera", protagonist: true},
		%{name: "Jason George", character: "Ben Warren", protagonist: true},
		%{name: "Grey Damon", character: "Jack Gibson"},
		%{name: "Barrett Doss", character: "Victoria Hughes"},
		%{name: "Alberto Frezza", character: "Ryan Tanner"},
		%{name: "Jay Hayden", character: "Travis Montgomery"},
		%{name: "Okieriete Onaodowan", character: "Dean Miller"},
		%{name: "Danielle Savre", character: "Maya Bishop"},
		%{name: "Miguel Sandoval", character: "Pruitt Herrera"},
		%{name: "Boris Kodjoe", character: "Captain Robert Sullivan"},
		%{name: "Brett Tucker", character: "Fire Chief Lucas Ripley"},
		%{name: "Sterling Sulieman", character: "Grant"},
		%{name: "Chandra Wilson", character: "Dr. Miranda Bailey"},
		%{name: "Brenda Song", character: "JJ"},
		%{name: "Dermot Mulroney", character: "Greg Tanner"},
		%{name: "Leslie Hope", character: "Battalion Chief Frankel"},
		%{name: "Marla Gibbs", character: "Edith"},
		%{name: "Chelsea Harris", character: "Nikki"},
		%{name: "Jake Borelli", character: "Dr. Levi Schmitt"},
		%{name: "Shawn Patrick Clifford", character: "Manager Cameron"}
	],
	description: "This spinoff of the critically acclaimed show Grey's Anatomy follows the lives of the men and women of firehouse station 19 in Seattle, Washington.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMTA4ODEwMjIzMjBeQTJeQWpwZ15BbWU4MDI5NTk2MzYz._V1_SX300.jpg",
	seasons: "2"
  },
  %{
	imdb_id: "tt0375355",
	title: "Joey",
	release_date: "2004-09-09",
	runtime: "22 min",
	classification: "12",
	genres: ["Comedy", "Romance"],
	writers: ["Shana Goldberg-Meehan", "Scott Silveri"],
	actors: [
		%{name: "Matt LeBlanc", character: "Joey Tribbiani", protagonist: true},
		%{name: "Andrea Anders", character: "Alex Garrett", protagonist: true},
		%{name: "Paulo Costanzo", character: "Michael Tribbiani", protagonist: true},
		%{name: "Jennifer Coolidge", character: "Bobbie Morganstern", protagonist: true},
		%{name: "Drea de Matteo", character: "Gina Tribbiani", protagonist: true},
		%{name: "Ben Falcone", character: "Howard"},
		%{name: "Miguel A. Núñez Jr.", character: "Zach"},
		%{name: "Adam Goldberg", character: "Jimmy"},
		%{name: "Alex Ball", character: "Todd"},
		%{name: "Tommy Perna", character: "Courier"},
		%{name: "Mädchen Amick", character: "Sara"},
		%{name: "Matt Letscher", character: "Eric Garrett"},
		%{name: "Gregory Harrison", character: "Dean"},
		%{name: "Matthew Mullany", character: "Carmen's Assistant"},
		%{name: "Simon Helberg", character: "Seth"},
		%{name: "Lucy Liu", character: "Lauren Beck"},
		%{name: "Richard Ruccolo", character: "Glen"},
		%{name: "Danneel Ackles", character: "London"},
		%{name: "Nat Faxon", character: "Bodie"},
		%{name: "Paula Cale", character: "Abby"}
	],
	description: "In this spin-off of Friends (1994), Joey Tribbiani moves to Los Angeles to pursue his acting career.",
	languages: ["English"],
	countries: ["USA"],
	poster: "https://m.media-amazon.com/images/M/MV5BMTAxNTYzMTQyNDBeQTJeQWpwZ15BbWU3MDk3MTA3MjE@._V1_SX300.jpg",
	seasons: "2"
  }
  
])
